name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
      
      - name: Use Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '>=17.7.2'
          cache: pnpm
      - name: install and check
        run: |
          pnpm install
          pnpm check
