name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      VITE_SANITY_PROJECT_ID: ''

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint code
        run: bun lint
